services:
  htmldiff-app:
    build: .
    container_name: htmldiff-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
    volumes:
      - ./logs:/app/logs
    networks:
      - htmldiff-network

networks:
  htmldiff-network:
    driver: bridge